[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
# vypne sledování souborů a odstraní ENOSPC chybu
fileWatcherType = "none"
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
