[supabase]
url = "https://aohzazxgyboglignckzt.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvaHphenhneWJvZ2xpZ25ja3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjMzMTYsImV4cCI6MjA2MTkzOTMxNn0.swG7YxHIpXMf0MGG8q2_1jEa43cUhvRsklZJzDDr5xY"

[groq]
api_key = "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"

[admin]
password = "ftvs2024"
